# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HerVoiceMatters', '0002_auto_20160513_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='height_img',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='width_img',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='height_img',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='width_img',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='height_img',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='width_img',
            field=models.IntegerField(default=0),
        ),
    ]
