# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-27 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HerVoiceMatters', '0007_auto_20160524_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='height_img',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='width_img',
            field=models.IntegerField(default=420),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='height_img',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='width_img',
            field=models.IntegerField(default=420),
        ),
    ]
