# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HerVoiceMatters', '0011_auto_20160531_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('fashion', 'FASHION'), ('delicacies', 'FOOD'), ('women', 'GIRL TALK')], default='fashion', max_length=11),
        ),
    ]
